### ISSUE TITLE
Apple Music Android App Support

### ISSUE THREAD

**Issue by NAUSHNIK52** [tgwizard/sls#232]
Please add ability to scrobble music from Apple Music Android App.

**Comment by HumbleBeeBumbleBee** [comment]
I have sent an email to support@apple.com requesting they broadcast song information so SLS can scrobble music played in Apple Music Android.

**Comment by NAUSHNIK52** [comment]
That's good. Please notify me about their answer.

**Comment by Efefefef** [comment]
So it there any news from Apple?

**Comment by HumbleBeeBumbleBee** [comment]
No news. Apple has its own social networking platforms. Not sure if they will add this.

**Comment by NAUSHNIK52** [comment]
If they add equalizer support then scrobbler may work.

**Comment by Sakurachansky** [comment]
That about SoundCloud app ( https://play.google.com/store/apps/details?id=com.soundcloud.android&hl=en). Your scrobbler doesn't work with it. Please add support for it

**Comment by HumbleBeeBumbleBee** [comment]
@Sakurachansky #144

**Comment by HumbleBeeBumbleBee** [comment]
Apple android doesn't seem to broadcast track information.

**Comment by kelchm** [comment]
@HumbleBeeBumbleBee, since it looks highly unlikely that Apple will ever add the necessary broadcasts to Apple Music, would it be reasonable to consider alternative methods of retrieving playback information?

Is there a way we could leverage accessibility functionality intended for vision impaired users to retrieve playback information from unsupported applications like Apple Music? I realize this isn't a trivial undertaking, but it would probably be the only way to ever scrobble from Apple Music on Android.

I'd be happy to contribute some time to such a feature, but given my rather limited experience with Android I doubt I would be able to without some hand-holding from someone with more experience.

**Comment by NAUSHNIK52** [comment]
@kelchm maybe this will help: https://github.com/artem-zinnatullin/android-wail-app/issues/8 ? WAIL is deprecated now.

**Comment by ibrokemypie** [comment]
+1

**Comment by 4-Eyes** [comment]
@HumbleBeeBumbleBee I've added a method for scrobbling Apple Music that uses notifications. I've tested it for several days and it appears to be stable and accurate. It has some limitations, like repeated songs won't currently work, but overall seems to do the job quite nicely.

**Comment by KazeSenoue** [comment]
I had the idea of reading notification data when I first read this issue a few weeks ago and thought about working on it, good to know it's been implemented. I'll give it a try and report any issues. Good work o/

**Comment by 4-Eyes** [comment]
@KazeSenoue if you (or anyone else) would like to test it right now [here](https://drive.google.com/open?id=0B2C0cv_a5TmgeTd1Y29YUkVnMjg) is a link to an APK of the current build that you could try. Some things to note would be:

- Firstly to enable the feature you need to go the application and tap on "Apple Music Support". Within this menu enable the notification listener. A warning will appear before redirecting you to settings where you should toggle the "AppleNotificationListener" to be enabled, there'll be another warning and then you should be fine to start testing.
- Without an internet connection every song will be treated as if it is 4 minutes long. This is because I'm currently getting song durations from last.fm and without internet this won't work. The reason for choosing 4 minutes as a default song length was that last.fm is supposed to srobble songs after they've played for 4 minutes.
- If notifications disappear from the bar at any point (this seems to happen a lot if you are in the apple music application) it will mess up scrobbling slightly. There are some features to try and help with this, but if you play an entire song without a notification appearing it will not be scrobbled.
- Repeated songs should now work, but again can be slightly hit and miss depending on the notifications provided.

**Comment by charliearlie** [comment]
@4-Eyes the apk isn't installing on my phone.

**Comment by 4-Eyes** [comment]
@charliearlie apologies for that. It should now be fixed (try the link in the old post, or [this](https://drive.google.com/open?id=0B2C0cv_a5TmgVFNVWTFnU3ByR3c) one if you want). It's also been updated to accommodate the recent changes in Apple Music application, with the introduction of Apple Music 2.0 on Android. It should also be backwards compatible if you still have the older version of the application.

**Comment by charliearlie** [comment]
@4-Eyes Thanks, I'm looking forward to testing it out. Going to see if I can contribute too. :)

**Comment by charliearlie** [comment]
@4-Eyes Unfortunately still not installing on my Samsung Galaxy S6 Edge+ though.

**Comment by syntech16** [comment]
This morning, I tried to install the APK in my phone, but I couldn't install it. I've now downloaded the new one and it seems to be working, it has scrobbled a track I've just played with v2.0 of Apple Music.

@charliearlie Do you already have a previous version of sls installed in your phone?

**Comment by charliearlie** [comment]
@syntech16 I have no previous version installed. It starts installing then just says "App not installed". Frustrating as to why.

**Comment by 4-Eyes** [comment]
@syntech16 well I'm not too sure what the issue could be there then. The only things I can think of doing would be to reboot the phone and double check you don't have any previous versions of the application installed. The later is because I'll have signed the APK different to the official version.

As a final resort you could always clone the source and build a version of it yourself.

**Comment by syntech16** [comment]
@charliearlie Do you have adb in your computer? If so, you could try to install it via "adb install sls-apple-scrobbling-dev.apk" in a command line. If it still fails, it will very likely tell you the reason.

For example, if you had previously installed sls from F-Droid, adb install would tell you:
_Failed to install sls-apple-scrobbling-dev.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.adam.aslfms signatures do not match the previously installed version; ignoring!]_

**Comment by charliearlie** [comment]
Cheers guys. Still not installing but I'll clone the source tomorrow and try building it myself.

**Comment by KazeSenoue** [comment]
Yup, same here using ADB. I get `Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]`.

**Comment by 4-Eyes** [comment]
Are you sure that you are using the last APK I built (the initial one was unsigned and the link has now been updated) and have you uninstalled the official version? If the problem persists cloning and building is probably the easiest solution.

**Comment by charliearlie** [comment]
I cloned and built a version for myself and now it works fine. Thanks.

**Comment by KazeSenoue** [comment]
Yup, I tried the last one you built. Gonna try building myself now.

**Comment by KazeSenoue** [comment]
I took the liberty of signing @4-Eyes 's build with some arbitrary values just for testing, and everything's been working great so far. If anyone wants to test it but doesn't feel like dealing with that, [here's](https://drive.google.com/file/d/0B0RnJP4WUvErWFBaa01qLXktdDA/view?usp=sharing) a link to it.

**Comment by steelrattus** [comment]
Thanks so much @4-Eyes for adding this support. I love Apple Music (aside from the stability of their Android app) so being able to scrobble the plays is awesome.

**Comment by steelrattus** [comment]
Looks like there's a bug with this version. Over the last 3 days I've had two tracks scrobble over and over again, for several hours, despite not being played.

**Comment by 4-Eyes** [comment]
@steelrattus sadly this is a trade off, it's either this, or repeating a song will only scrobble once. The reason this happens is the app is only listening to notifications (that appear in the notification tray) from Apple Music and quite often these notification will disappear, so it's basically impossible to tell when a song has finished unless a paused state notification appears (notification has a play button on it). Due to this limitation it's also impossible to tell when someone is repeating a song, therefore there is a timer in the scrobbler that fires off an event after the length of time the song should last, if there haven't been any new notifications during that time it assumes the song is repeating. The easiest solution to this is simply to make sure the paused state notification appears in the notification tray. That or I could add a feature to disable the listening for repeated plays of the same track.

**Comment by steelrattus** [comment]
@4-Eyes I'll keep an eye out for the pause state. At least one of the tracks oddly wasn't the last track I played, yet had scrobbled over and over for about 10 hours, when fortunately I spotted it! When I looked back I noticed the other track that had also scrobbled for 12 hours or so. Thanks for the help, and again thanks for getting Apple Music to scrobble!

**Comment by steelrattus** [comment]
Unfortunately it's still happening. I thought I'd figured out the cause, which was switching from Apple Music to another player, then the last track on Apple Music kept scrobbling, but even pausing the track before switching doesn't seem to help. Also my podcast app is scrobbling many times, presumably because podcasts can be an hour long, and it scrobbles every 4 minutes?

It would be fab if you could add the duplicate check option. I'd much rather it stop this behaviour, as I'm not too worried about having super accurate duplicate scrobbling. It takes quite a while to delete all the incorrect scrobbles from Last.FM.

**Comment by gafel** [comment]
Just came here to say what @steelrattus mentioned above about tracks scrobbling over and over. My experience was a song with length of 1:39. I played the song once and then noticed days later that it had scrobbled every 1:39 for 3 days straight (at least one thousand scrobbles of said track).

Other than that one instance Apple Music scrobbling worked pretty well.

**Comment by 4-Eyes** [comment]
@steelrattus & @gafel sorry for the delay in responding. The repeated songs feature is now optional (there's a new setting for it). I've made a new APK for it [here](https://drive.google.com/open?id=0B2C0cv_a5TmgUDhya1JnemFOMDA). It should also be noted that I haven't actually tested it properly, but it should work in theory (famous last words).

**Comment by steelrattus** [comment]
Thanks @4-Eyes, much appreciated! Will give it a test...

**Comment by steelrattus** [comment]
I'm still getting some repeated plays. Not sure if it's caused by errant notifications. For example I played a few tracks, then the scrobbling seemed to get stuck on a track that was scrobbling every 5 or so minutes, even though new tracks were playing.

**Comment by 4-Eyes** [comment]
That's more likely to be due to overlap checking, which is in there to try and help when notifications disappear and then reappear, but the notification doesn't stay long enough to count as a scrobble. Basically Apple are mean and their notifications don't even stick around all the time (unlike Deezer, Spotify, Tidal, SoundCloud and basically every other music service). So sadly it's about as good as I can get it.

**Comment by steelrattus** [comment]
Just to double check, under the Apple Music Support options, should we be enabling "Enable repeating of tracks"? For those of us that don't want to see tracks repeated when played repeatedly, and more so to get around the issue of tracks showing repeatedly even when not playing repeatedly? Thanks!

**Comment by 4-Eyes** [comment]
Nope, that should be turned off.

**Comment by steelrattus** [comment]
Ah! This may explain why I was still getting duplicates.

Although oddly, if I turn it off, go back to the main menu, then back to the Apple Music Options, it is enabled again.

**Comment by 4-Eyes** [comment]
Ah, that sounds like a bug. Looking at the code it was a bug, which I have now fixed. Old link should still work, or [here](https://drive.google.com/open?id=0B2C0cv_a5TmgUDhya1JnemFOMDA) for the new APK.

**Comment by perfectayush** [comment]
@4-Eyes I was facing an issue with SLS apple scrobbling. I recently switched my phone. It now has Android 7.1.1. The apk you shared was working on my old phone. It is not working on android 7.1.1 (or is it because of the new apple music version 2.0.1, I am not sure). So what I did was, built apk from your branch and checked for Logcat in Android Studio. For class com.adam.aslfms:remote I was getting:

> java.lang.ClassCastException: java.util.concurrent.CopyOnWriteArrayList cannot be cast to java.util.ArrayList

which points to this line here: https://github.com/4-Eyes/sls/blob/master/app/src/main/java/com/adam/aslfms/service/applemusic/NotificationService.java#L74. 

I just switched the class from **ArrayList** to **CopyOnWriteArrayList**. And the service started working for me. I thought, to point this out to you. I am not an android or java developer, and maybe this requires fixing by a more seasoned developer, with a better approach. Thanks for your effort.

**Comment by steelrattus** [comment]
Thanks @4-Eyes, much appreciated!

**Comment by KazeSenoue** [comment]
I'm still using the first version of the APK with none of the problems listed here. Just thought I'd let you guys know they're probably device specific.

**Comment by beschoenen** [comment]
Try this:
1. Play a song
2. Pause it via the notification
3. Swipe the notification away
4. Swipe Apple Music from the recent app screen
The Apple music notification will re-appear, let it be for a while and you'll see the scrobbles pile up.

**Comment by aryamanarora** [comment]
The apk doesn't install on the Nexus 5, Android 6.0.1

**Comment by kurtph1969** [comment]
Hi, new here. I am using the link from Kxze May 5 on my Samsung Galax S6 and I can confirm it is working perfectly. This is a life saver as I just got 6 months Apple Music Free. If this app makes it to the Play Store I will happily buy it 🥇

**Comment by kurtph1969** [comment]
One thing I have noticed, I am getting duplicate Scrobbles of the last track played... I don't see Apple Music Support options' - where is that please?

**Comment by steelrattus** [comment]
I've started using Scroball, which seems pretty reliable. Referenced on this useful page https://getsatisfaction.com/lastfm/topics/more-ways-to-scrobble
